version: '3'

services:
  db:
    image: postgres
    container_name: 'db'
    environment: 
        - POSTGRES_DB=bankapp
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=qwerty

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python src/main.py
    depends_on:
      - db
      - elasticsearch
    environment:
      PYTHONPATH: .src
    volumes:
      - .:/src
    ports:
      - "8000:8000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
